server:
  port: 8080

spring:
  datasource:
    username: root
    password: Heu2018065220.
    url: jdbc:mysql://localhost:3306/db01?useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html